### ISSUE TITLE
Chapter 6: ng2-bootstrap TypeError

### ISSUE THREAD

**Issue by ttchongtc** [PacktPublishing/ASPdotNET-Core-and-Angular-2#10]
For chapter 6, I keep getting this error:
TypeError: Cannot read property 'Output' of undefined

Here's my package.json config. I also tried the version listed in the book (2.14.1 for moment and 1.0.24 for ng2-bootstrap) but same error.

{
  "version": "1.0.0",
  "name": "opengamelistwebapp",
  "private": true,
  "dependencies": {
    "@angular/common": "2.4.4",
    "@angular/compiler": "2.4.4",
    "@angular/core": "2.4.4",
    "@angular/forms": "2.4.4",
    "@angular/http": "2.4.4",
    "@angular/platform-browser": "2.4.4",
    "@angular/platform-browser-dynamic": "2.4.4",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.4.4",
    "core-js": "^2.4.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "^0.19.37",
    "typings": "^1.3.2",
    "zone.js": "0.8.4",
    "moment": "2.17.1",
    "ng2-bootstrap": "1.4.0"
  },
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-clean": "^0.3.2",
    "gulp-concat": "^2.6.0",
    "gulp-less": "3.3.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-typescript": "^2.13.6",
    "gulp-uglify": "^2.0.0",
    "typescript": "2.2.1"
  },
  "scripts": {
    "postinstall": "typings install dt~es6-shim --global"
  }
}

**Comment by ttchongtc** [comment]
Please help...

**Comment by Darkseal** [comment]
Hello,
you shouldn't worry about ng2-bootstrap package because that part has entirely been removed from the book, thus it's never ever used in the source code. Just skip/avoid putting the references there and you should be good!
