### ISSUE TITLE
Loading all js libraries on initial load

### ISSUE THREAD

**Issue by AmanpreetSingh-GitHub** [PacktPublishing/ASPdotNET-Core-and-Angular-2#11]
I am following your book and after working thru Chapter 1 and running it found that all the js libraries are getting loaded. Thats won't be efficient as why are we loading unwanted libraries.

**Comment by Darkseal** [comment]
Hello and thanks for purchasing the book.

The project is using SystemJS dynamic module loading capabilities (see pages 52-54). The configuration file is **systemjs.configuration.js**, which is meant to work with the book code samples you will find in the book (the Chapter01 code be also extended later on): however, you can also configure it accordingly to your needs or switch to another JS module loader such as the great yet less straightforward [Webpack bundler](https://webpack.github.io/).

For more info regarding **SystemJS** and how it works, read here:
http://blog.angular-university.io/introduction-to-es6-modularity-the-jspm-package-manager-and-the-systemjs-loader/
https://www.sitepoint.com/modular-javascript-systemjs-jspm/
