### ISSUE TITLE
post script typings install doesn't work

### ISSUE THREAD

**Issue by yalin78** [PacktPublishing/ASPdotNET-Core-and-Angular-2#4]
When i save package.json file after writing following it fails.

"scripts": {
    "postinstall": "typings install dt~core-js --global"
  }

PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\npm.CMD" install
> opengamelistwebapp@1.0.0 postinstall C:\Development\OpenGameList\OpenGameListWebApp
> typings install dt~core-js --global
typings ERR! message Unable to connect to "https://api.typings.org/entries/dt/core-js/versions/latest"
typings ERR! caused by unable to get local issuer certificate
typings ERR! 
typings ERR! cwd C:\Development\OpenGameList\OpenGameListWebApp
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe" "C:\\Development\\OpenGameList\\OpenGameListWebApp\\node_modules\\typings\\dist\\bin.js" "install" "dt~core-js" "--global"
typings ERR! node -v v5.4.1
typings ERR! typings -v 2.0.0
typings ERR! code EUNAVAILABLE
typings ERR! 
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
npm WARN @angular/core@2.0.0-rc.5 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/http@2.0.0-rc.5 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! opengamelistwebapp@1.0.0 postinstall: `typings install dt~core-js --global`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opengamelistwebapp@1.0.0 postinstall script 'typings install dt~core-js --global'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opengamelistwebapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install dt~core-js --global
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opengamelistwebapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opengamelistwebapp
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Development\OpenGameList\OpenGameListWebApp\npm-debug.log
[?25h
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\npm.CMD" install
> opengamelistwebapp@1.0.0 postinstall C:\Development\OpenGameList\OpenGameListWebApp
> typings install dt~core-js --global
typings ERR! message Unable to connect to "https://api.typings.org/entries/dt/core-js/versions/latest"
typings ERR! caused by unable to get local issuer certificate
typings ERR! 
typings ERR! cwd C:\Development\OpenGameList\OpenGameListWebApp
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe" "C:\\Development\\OpenGameList\\OpenGameListWebApp\\node_modules\\typings\\dist\\bin.js" "install" "dt~core-js" "--global"
typings ERR! node -v v5.4.1
typings ERR! typings -v 2.0.0
typings ERR! code EUNAVAILABLE
typings ERR! 
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
npm WARN @angular/core@2.0.0-rc.5 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/http@2.0.0-rc.5 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! opengamelistwebapp@1.0.0 postinstall: `typings install dt~core-js --global`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opengamelistwebapp@1.0.0 postinstall script 'typings install dt~core-js --global'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opengamelistwebapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install dt~core-js --global
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opengamelistwebapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opengamelistwebapp
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Development\OpenGameList\OpenGameListWebApp\npm-debug.log
[?25h

**Comment by Darkseal** [comment]
Hello and thanks for your feedback. 

I suggest you to try the following:

- Uninstall any TypeScript for Visual Studio you might have in your development machine
- Install [TypeScript for Visual Studio 2.1.4.0](https://www.microsoft.com/en-US/download/details.aspx?id=48593), which should fix your issue

Also take a look to [the following issue](https://github.com/PacktPublishing/ASPdotNET-Core-and-Angular-2/issues/1#issuecomment-268999327) for further details about TS and typings-related problems.

**Comment by Darkseal** [comment]
I'm adding this comment to share this workaround I found to overcome a rather common issue which is happening due to [this DefinitelyTyped/core-js issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15140) which strongly affects the Visual Studio TypeScript compiler.

The compilation errors you can receive are the following:

> Error	TS2693	Build:'Map' only refers to a type, but is being used as a value here.	
> Error	TS2693	Build:'Promise' only refers to a type, but is being used as a value here.	
> Error	TS2693	Build:'Set' only refers to a type, but is being used as a value here.	
> Error	TS2304	Build:Cannot find name 'Iterable'.	
> Error	TS2304	Build:Cannot find name 'IterableIterator'.
> Error	TS2304	Build:Cannot find name 'MapConstructor'.	
> Error	TS2304	Build:Cannot find name 'Iterator'.	
> Error	TS2304	Build:Cannot find name 'PromiseConstructor'.	
> Error	TS2304	Build:Cannot find name 'PropertyKey'.	
> Error	TS2304	Build:Cannot find name 'SetConstructor'.	
> Error	TS2304	Build:Cannot find name 'Symbol'.	
> Error	TS2304	Build:Cannot find name 'WeakMapConstructor'.	
> Error	TS2304	Build:Cannot find name 'WeakSetConstructor'.
> Error	TS2339	Build:Property 'for' does not exist on type 'SymbolConstructor'.	
> Error	TS2339	Build:Property 'hasInstance' does not exist on type 'SymbolConstructor'.	
> Error	TS2339	Build:Property 'isConcatSpreadable' does not exist on type 'SymbolConstructor'.
> Error	TS2339	Build:Property 'iterator' does not exist on type 'SymbolConstructor'.
> Error	TS2339	Build:Property 'keyFor' does not exist on type 'SymbolConstructor'.
> Error	TS2339	Build:Property 'match' does not exist on type 'SymbolConstructor'.
> Error	TS2339	Build:Property 'replace' does not exist on type 'SymbolConstructor'.
> Error	TS2339	Build:Property 'search' does not exist on type 'SymbolConstructor'.
> Error	TS2339	Build:Property 'species' does not exist on type 'SymbolConstructor'.
> Error	TS2339	Build:Property 'split' does not exist on type 'SymbolConstructor'.
> Error	TS2339	Build:Property 'toPrimitive' does not exist on type 'SymbolConstructor'.
> Error	TS2339	Build:Property 'toStringTag' does not exist on type 'SymbolConstructor'.	
> Error	TS2339	Build:Property 'unscopables' does not exist on type 'SymbolConstructor'.

.. and so on.

The problem is due to an internal issue within that third-party library. We can fix that by specifying a fixed/unaffected version, so our project won't update it anymore with the latest build (which is causing the issue).

In order to do that open the project's **package.json** file and replace this:

```
  "scripts": {
    "postinstall": "typings install dt~core-js --global"
  }
```

with this:

```
  "scripts": {
    "postinstall": "typings install dt~core-js@0.9.7+20161130133742 --global"
  }
```

I will release a GitHub patch later today to fix the source code as well.

**N.B.**: There are many other possible ways to work around this problem: I chose this one because it doesn't require any significative change to the source code, thus making it easier to pull off for those who purchased the book.
