### ISSUE TITLE
Bad request with authservice.get()

### ISSUE THREAD

**Issue by cicciuzzo2000** [PacktPublishing/ASPdotNET-Core-and-Angular-2#8]
Hi,

why when I call the authservice.get() in ngOnInit event of app.component.ts  I obtain a bad request?

How I can to obtain all information of current user?

ngOnInit() {
        var auth = this.authService.getAuth();
        alert(auth.access_token);
        this.currentUser = this.authService.get().subscribe(
            user => {
                this.currentUser.UserName = user.UserName;
            });
    }

BR

**Comment by Darkseal** [comment]
I cannot reproduce your error... Have you tried that using the GitHub source code without altering it in any way?
