### ISSUE TITLE
user.identity.isauthenticated always false ???

### ISSUE THREAD

**Issue by cicciuzzo2000** [PacktPublishing/ASPdotNET-Core-and-Angular-2#9]
public async Task<string> GetCurrentUserId()
        {
            // if the user is not authenticated, throw an exception
            **if (!User.Identity.IsAuthenticated)**
                throw new NotSupportedException();

            var info = await SignInManager.GetExternalLoginInfoAsync();
            if (info == null)
                // internal provider
                return User.FindFirst(ClaimTypes.NameIdentifier).Value;
            else
            {
                // external provider
                var user = await UserManager.FindByLoginAsync(
                    info.LoginProvider,
                    info.ProviderKey);
                if (user == null) throw new NotSupportedException();
                return user.Id;
            }
        }
Why user.identity.isauthenticated always false ?
This raise a Bad Request!

thanks

**Comment by Darkseal** [comment]
Please be more specific: if IsAuthenticated is false, it means that something went wrong during the authentication phase. The exception helps you acknowledge that something went wrong in OTHER sections of your code.

**Comment by cicciuzzo2000** [comment]
hi,
when I create a new user with the form all work fine, after I try the login with the new credential also work fine, because there are the component that are conditioned by this
```
isLoggedIn(): boolean {
        return localStorage.getItem(this.authKey) != null;
    }
```
 The problem is when this method from angular , I obtain a bad request
```
get() {
        return this.http.get("api/Accounts")
            .map(response => <User>response.json());
    }
```
I modified the code in account controller

```
public async Task<IActionResult> Get()
        {
            //var id = await GetCurrentUserId();  >>>> **COMMENTED** <<<<
            var id = User.FindFirst(ClaimTypes.NameIdentifier).Value;  >>>> **ADD THIS** <<<<
            var user = DbContext.Users.Where(i => i.Id == id).FirstOrDefault();
            if (user != null) return new JsonResult(new UserViewModel()
            {
                Type = user.Type,
                UserName = user.UserName,
                Email = user.Email,
                DisplayName = user.DisplayName,
                PhoneNumber = user.PhoneNumber,
                DisplayPhoneNumber = user.DisplayPhoneNumber,
                Description = user.Description

            }, DefaultJsonSettings);
            else return NotFound(new { error = String.Format("User ID {0} has not been found", id) });
        }
```
I downloaded the code from github

**Comment by cicciuzzo2000** [comment]
If I use thi code don't work

```
 public async Task<string> GetCurrentUserId()
        {
            // if the user is not authenticated, throw an exception
            if (!User.Identity.IsAuthenticated)
                throw new NotSupportedException();

            var info = await SignInManager.GetExternalLoginInfoAsync();
            if (info == null)
                // internal provider
                return User.FindFirst(ClaimTypes.NameIdentifier).Value;
            else
            {
                // external provider
                var user = await UserManager.FindByLoginAsync(
                    info.LoginProvider,
                    info.ProviderKey);
                if (user == null) throw new NotSupportedException();
                return user.Id;
            }
}
```
I want use the external login but only identity

**Comment by Darkseal** [comment]
Are you sure you're using the same builds/versions of the .NET Core components? Things have changed from October, if you update your packages (Middleware, ASP.NET Core version & so on) you'll have to change the source code as well according to the breaking changes. They *did* change a lot there, so it will require some work. I'm working on a updated version of the book to fix these kind of issues, my suggestion (until then) is to try to use the versions/builds used by the book and try to grasp the big picture. Once you do that, you can easily adapt the code to the ASP.NET Core ongoing changes.
